
/*==============================================================
  MÓDULO 2  –  DDL con TABLESPACE asignado
  (Tablas + índices externos + FKs)
==============================================================*/

/*================================================================
  1. ÁREA CLIENTES  –  TS_CLIENTES_DATA / TS_CLIENTES_IDX
================================================================*/

DROP TABLE CLIENTE CASCADE CONSTRAINTS;

CREATE TABLE CLIENTE (
  CLAVE_CLIENTE_ID          NUMBER(10,0) GENERATED ALWAYS AS IDENTITY NOT NULL,
  CURP_CLIENTE              VARCHAR2(40) NOT NULL,
  NOMBRE_CLIENTE            VARCHAR2(40) NOT NULL,
  ESTADO_CIVIL_CLIENTE      VARCHAR2(40) NOT NULL,
  EDAD_CLIENTE              VARCHAR2(40) NULL,
  NIVEL_ESTUDIOS_CLIENTE    VARCHAR2(40) NOT NULL,
  OCUPACION_CLIENTE         VARCHAR2(40) NOT NULL,
  TELEFONO_CLIENTE          VARCHAR2(40) NOT NULL,
  CONSTRAINT CLIENTE_PK PRIMARY KEY (CLAVE_CLIENTE_ID)
) TABLESPACE TS_CLIENTES_DATA;

CREATE TABLE INVITADO (
    INVITADO_ID         VARCHAR2(40) NOT NULL,
    NOMBRE_COMPLETO     VARCHAR2(40) NOT NULL,
    EDAD_INVITADO       VARCHAR2(40) NOT NULL,
    PARENTESCO_INVITADO VARCHAR2(40) NOT NULL,
    OCUPACION_INVITADO  VARCHAR2(40) NOT NULL,
    CLAVE_CLIENTE_ID    NUMBER(10,0),
    CONSTRAINT INVITADO_PK PRIMARY KEY (INVITADO_ID)
) TABLESPACE TS_CLIENTES_DATA;

CREATE INDEX CLAVE_INVITADO_CLIENTE_FK
        ON INVITADO (CLAVE_CLIENTE_ID)
TABLESPACE TS_CLIENTES_IDX;

CREATE TABLE AUTO_CLIENTE (
    PLACA               VARCHAR2(40) NOT NULL,
    MODELO_AUTO_CLIENTE VARCHAR2(40) NOT NULL,
    MARCA_AUTO_CLIENTE  VARCHAR2(40) NOT NULL,
    CONSTRAINT AUTO_CLIENTE_PK PRIMARY KEY (PLACA)
) TABLESPACE TS_CLIENTES_DATA;

/*--------------------------------------------------------------
  FKs (clientes ⇆ invitados / autos)
--------------------------------------------------------------*/
ALTER TABLE INVITADO
  ADD CONSTRAINT CLAVE_INVITADO_CLIENTE_FK
  FOREIGN KEY (CLAVE_CLIENTE_ID) REFERENCES CLIENTE(CLAVE_CLIENTE_ID);

/*================================================================
  2. ÁREA MEMBRESÍAS  –  TS_MEMBRESIAS_DATA / TS_MEMBRESIAS_IDX
================================================================*/
CREATE TABLE ESTADO_MEMBRESIA (
    ESTADO_MEMBRESIA        VARCHAR2(40) NOT NULL,
    NOMBRE_ESTADO_MEMBRESIA VARCHAR2(40) NOT NULL
                              CONSTRAINT CK_NOMBRE_ESTADO_MEMBRESIA
                              CHECK (UPPER(NOMBRE_ESTADO_MEMBRESIA)
                                     IN ('VIGENTE','ADEUDO','SUSPENDIDA','CANCELADA')),
    DESCRIPCION_ESTADO      VARCHAR2(40) NOT NULL,
    CONSTRAINT ESTADO_MEMBRESIA_PK PRIMARY KEY (ESTADO_MEMBRESIA)
) TABLESPACE TS_MEMBRESIAS_DATA;

CREATE TABLE TARJETA (
    NO_TARJETA             VARCHAR2(40) NOT NULL,
    ANIO_TARJETA           VARCHAR2(40),
    MES_EXPIRACION_TARJETA VARCHAR2(40),
    TIPO_TARJETA           VARCHAR2(40),
    CONSTRAINT TARJETA_PK PRIMARY KEY (NO_TARJETA)
) TABLESPACE TS_MEMBRESIAS_DATA;

CREATE TABLE CLIENTE_MEMBRESIA (
    CLAVE_CLIENTE_ID               NUMBER(10,0) NOT NULL,
    COSTO_MENSUAL                  BINARY_FLOAT NOT NULL,
    NUM_MAX_INVITADOS              NUMBER(40,0) NOT NULL,
    TIPO_TARJETA_CLIENTE_MEMBRESIA VARCHAR2(40),
    CLIENTE_ASOCIADO_MEMBRESIA     VARCHAR2(40),
    FECHA_REGISTRO_MEMBRESIA       VARCHAR2(40),
    ESTADO_MEMBRESIA               VARCHAR2(40) NOT NULL,
    NO_TARJETA                     VARCHAR2(40),
    CONSTRAINT CLIENTE_MEMBRESIA_PK PRIMARY KEY (CLAVE_CLIENTE_ID)
) TABLESPACE TS_MEMBRESIAS_DATA;

CREATE INDEX CLAVE_CLIENTE_MEM_CLIENTE_FK
        ON CLIENTE_MEMBRESIA (CLAVE_CLIENTE_ID)
TABLESPACE TS_MEMBRESIAS_IDX;

CREATE INDEX CLAVE_ESTADO_MEMBRESIA_FK
        ON CLIENTE_MEMBRESIA (ESTADO_MEMBRESIA)
TABLESPACE TS_MEMBRESIAS_IDX;

CREATE INDEX CLAVE_TARJETA_MEMBRESIA_FK
        ON CLIENTE_MEMBRESIA (NO_TARJETA)
TABLESPACE TS_MEMBRESIAS_IDX;

CREATE TABLE HISTORIAL_MEMBRESIA (
    HISTORIAL_MEMBRESIA_ID VARCHAR2(40) NOT NULL,
    FECHA_CAMBIO_ESTADO    VARCHAR2(40) NOT NULL,
    ESTADO_MEMBRESIA       VARCHAR2(40),
    CLAVE_CLIENTE_ID       NUMBER(10,0) NOT NULL,
    CONSTRAINT HISTORIAL_MEMBRESIA_PK PRIMARY KEY (HISTORIAL_MEMBRESIA_ID)
) TABLESPACE TS_MEMBRESIAS_DATA;

CREATE INDEX CLAVE_HIST_HESTADO_MEMBRESIA_FK
        ON HISTORIAL_MEMBRESIA (ESTADO_MEMBRESIA)
TABLESPACE TS_MEMBRESIAS_IDX;

CREATE INDEX CLAVE_HIST_CLIENTE_FK
        ON HISTORIAL_MEMBRESIA (CLAVE_CLIENTE_ID)
TABLESPACE TS_MEMBRESIAS_IDX;

/*--------------------------------------------------------------
  FKs (membresías)
--------------------------------------------------------------*/
ALTER TABLE CLIENTE_MEMBRESIA
  ADD CONSTRAINT CLAVE_CLIENTE_MEM_CLIENTE_FK
  FOREIGN KEY (CLAVE_CLIENTE_ID) REFERENCES CLIENTE(CLAVE_CLIENTE_ID);

ALTER TABLE CLIENTE_MEMBRESIA
  ADD CONSTRAINT CLAVE_ESTADO_MEMBRESIA_FK
  FOREIGN KEY (ESTADO_MEMBRESIA) REFERENCES ESTADO_MEMBRESIA(ESTADO_MEMBRESIA);

ALTER TABLE CLIENTE_MEMBRESIA
  ADD CONSTRAINT CLAVE_TARJETA_MEMBRESIA_FK
  FOREIGN KEY (NO_TARJETA) REFERENCES TARJETA(NO_TARJETA);

ALTER TABLE HISTORIAL_MEMBRESIA
  ADD CONSTRAINT CLAVE_HIST_CLIENTE_FK
  FOREIGN KEY (CLAVE_CLIENTE_ID) REFERENCES CLIENTE_MEMBRESIA(CLAVE_CLIENTE_ID);

ALTER TABLE HISTORIAL_MEMBRESIA
  ADD CONSTRAINT CLAVE_HIST_HESTADO_MEMBRESIA_FK
  FOREIGN KEY (ESTADO_MEMBRESIA) REFERENCES ESTADO_MEMBRESIA(ESTADO_MEMBRESIA);

/*================================================================
  3. ÁREA VISITAS  –  TS_VISITAS_DATA / TS_VISITAS_IDX
================================================================*/
CREATE TABLE VISITA_CLIENTE (
    VISITA_CLIENTE_ID          VARCHAR2(40) NOT NULL,
    RCENTRO_ID                 VARCHAR2(40) NOT NULL,
    FECHA_LLEGADA_REGISTRO     TIMESTAMP(6) NOT NULL,
    FECHA_SLIDA_REGISTRO       TIMESTAMP(6) NOT NULL,
    CANTIDAD_PERSONAS_REGISTRO VARCHAR2(40) NOT NULL,
    CLAVE_CLIENTE_ID           NUMBER(10,0),
    PLACA                      VARCHAR2(40),
    CONSTRAINT VISITA_CLIENTE_PK PRIMARY KEY (VISITA_CLIENTE_ID)
) TABLESPACE TS_VISITAS_DATA;

CREATE INDEX CLAVE_CLIENTE_FK
        ON VISITA_CLIENTE (CLAVE_CLIENTE_ID)
TABLESPACE TS_VISITAS_IDX;

CREATE INDEX CLAVE_AUTO_CILENTE_FK
        ON VISITA_CLIENTE (PLACA)
TABLESPACE TS_VISITAS_IDX;

CREATE TABLE VISITA_INVITADO (
    INVITADO_ID       VARCHAR2(40) NOT NULL,
    VISITA_CLIENTE_ID VARCHAR2(40) NOT NULL,
    CONSTRAINT VISITA_INVITADO_PK PRIMARY KEY (INVITADO_ID, VISITA_CLIENTE_ID)
) TABLESPACE TS_VISITAS_DATA;

CREATE INDEX INVITADO_ID_IX
        ON VISITA_INVITADO (INVITADO_ID)
TABLESPACE TS_VISITAS_IDX;

CREATE INDEX CLAVE_VISITA_INVITADO_FK
        ON VISITA_INVITADO (VISITA_CLIENTE_ID)
TABLESPACE TS_VISITAS_IDX;

/*--------------------------------------------------------------
  FKs (visitas)
--------------------------------------------------------------*/
ALTER TABLE VISITA_CLIENTE
  ADD CONSTRAINT CLAVE_AUTO_CILENTE_FK
      FOREIGN KEY (PLACA) REFERENCES AUTO_CLIENTE(PLACA);

ALTER TABLE VISITA_CLIENTE
  ADD CONSTRAINT CLAVE_CLIENTE_FK
      FOREIGN KEY (CLAVE_CLIENTE_ID) REFERENCES CLIENTE(CLAVE_CLIENTE_ID);

ALTER TABLE VISITA_INVITADO
  ADD CONSTRAINT RefINVITADO59
      FOREIGN KEY (INVITADO_ID) REFERENCES INVITADO(INVITADO_ID);

ALTER TABLE VISITA_INVITADO
  ADD CONSTRAINT CLAVE_VISITA_INVITADO_FK
      FOREIGN KEY (VISITA_CLIENTE_ID) REFERENCES VISITA_CLIENTE(VISITA_CLIENTE_ID);

/*================================================================
  4. ÁREA ACTIVIDAD–PARTICIPACIÓN  –  TS_ACTPART_*
================================================================*/
CREATE TABLE ACTIVIDAD_PARTICIPACION (
    ACTIVIDAD_PARTICIPACION_ID VARCHAR2(40) NOT NULL,
    RACTVIDAD_ID               VARCHAR2(40) NOT NULL,
    TIEMPO_FIN_PARTICIPACION_ACTIVIDAD    TIMESTAMP(6) NOT NULL,
    TIEMPO_INICIO_PARTICIPACION_ACTIVIDAD TIMESTAMP(6) NOT NULL,
    INVITADO_ID                VARCHAR2(40),
    CLAVE_CLIENTE_ID           NUMBER(10,0),
    CONSTRAINT ACTIVIDAD_PARTICIPACION_PK PRIMARY KEY (ACTIVIDAD_PARTICIPACION_ID)
) TABLESPACE TS_ACTPART_DATA;

CREATE INDEX CLAVE_INVITADO_ACTIVIDAD_FK
        ON ACTIVIDAD_PARTICIPACION (INVITADO_ID)
TABLESPACE TS_ACTPART_IDX;

CREATE INDEX CLAVE_CLIENTE_PK     -- (nombre heredado del script original)
        ON ACTIVIDAD_PARTICIPACION (CLAVE_CLIENTE_ID)
TABLESPACE TS_ACTPART_IDX;

/*--------------------------------------------------------------
  FKs (actividad participación)
--------------------------------------------------------------*/
ALTER TABLE ACTIVIDAD_PARTICIPACION
  ADD CONSTRAINT CLAVE_INVITADO_ACTIVIDAD_FK
      FOREIGN KEY (INVITADO_ID) REFERENCES INVITADO(INVITADO_ID);

ALTER TABLE ACTIVIDAD_PARTICIPACION
  ADD CONSTRAINT CLAVE_CLIENTE_PK
      FOREIGN KEY (CLAVE_CLIENTE_ID) REFERENCES CLIENTE(CLAVE_CLIENTE_ID);

