/*==============================================================
  CENTROS  (datos + índices)  –  TS_CENTROS_*
==============================================================*/
CREATE TABLE ASOCIACION (
    ASOCIACION_ID        VARCHAR2(40) NOT NULL,
    NOMBRE_ASOCIACION    VARCHAR2(40) NOT NULL,
    CALLE_ASOCIACION     VARCHAR2(40) NOT NULL,
    MUNICIPIO_ASOCIACION VARCHAR2(40) NOT NULL,
    COLONIA_ASOCIACION   VARCHAR2(40) NOT NULL,
    TELEFONO_ASOCIACION  VARCHAR2(40) NOT NULL,
    CONSTRAINT ASOCIACION_PK PRIMARY KEY (ASOCIACION_ID)
) TABLESPACE TS_CENTROS_DATA;

CREATE TABLE CENTRO_VACACIONAL (
    CENTRO_ID                 VARCHAR2(40) NOT NULL,
    UBICACION_LATITUD_CENTRO  BINARY_FLOAT NOT NULL,
    UBICACION_LONGITUD_CENTRO BINARY_FLOAT NOT NULL,
    ASOCIACION_ID             VARCHAR2(40) NOT NULL,
    CONSTRAINT CENTRO_VACACIONAL_PK PRIMARY KEY (CENTRO_ID)
) TABLESPACE TS_CENTROS_DATA;

CREATE INDEX CLAVE_ASOCIACION_CENTRO_VAC_FK
        ON CENTRO_VACACIONAL (ASOCIACION_ID)
TABLESPACE TS_CENTROS_IDX;

/*==============================================================
  EMPLEADOS / LÍDERES  –  TS_EMPLEADOS_*
==============================================================*/
CREATE TABLE EMPLEADO (
    EMPLEADO_ID               VARCHAR2(40) NOT NULL,
    NOMBRE_EMPLEADO           VARCHAR2(40) NOT NULL,
    APELLIDO_PATERNO_EMPLEADO VARCHAR2(40) NOT NULL,
    APELLIDO_MATERNO_EMPLEADO VARCHAR2(40) NOT NULL,
    TELEFONO_EMPLEADO         VARCHAR2(40) NOT NULL,
    ASOCIACION_ID             VARCHAR2(40) NOT NULL,
    EMPLEADO_RESPONSABLE_ID   VARCHAR2(40),
    CONSTRAINT EMPLEADO_PK PRIMARY KEY (EMPLEADO_ID)
) TABLESPACE TS_EMPLEADOS_DATA;

CREATE INDEX CLAVE_ASOC_EMPLEADO_FK
        ON EMPLEADO (ASOCIACION_ID)
TABLESPACE TS_EMPLEADOS_IDX;

CREATE INDEX CLAVE_EMP_EMP_FK
        ON EMPLEADO (EMPLEADO_RESPONSABLE_ID)
TABLESPACE TS_EMPLEADOS_IDX;

CREATE TABLE LIDER (
    EMPLEADO_ID             VARCHAR2(40) NOT NULL,
    ANIOS_EXPERIENCIA_LIDER NUMBER(40,0) NOT NULL,
    ESPECIALIZACION_LIDER   VARCHAR2(40) NOT NULL,
    CONSTRAINT LIDER_PK PRIMARY KEY (EMPLEADO_ID)
) TABLESPACE TS_EMPLEADOS_DATA;

CREATE INDEX EMPLEADO_ID_IX
        ON LIDER (EMPLEADO_ID)
TABLESPACE TS_EMPLEADOS_IDX;

CREATE TABLE CENTRO_LIDER (
    CENTRO_ID   VARCHAR2(40) NOT NULL,
    EMPLEADO_ID VARCHAR2(40) NOT NULL,
    CONSTRAINT CENTRO_LIDER_PK PRIMARY KEY (CENTRO_ID, EMPLEADO_ID)
) TABLESPACE TS_EMPLEADOS_DATA;

CREATE INDEX CLAVE_CENTRO_VAC_CENTRO_LID_FK
        ON CENTRO_LIDER (CENTRO_ID)
TABLESPACE TS_EMPLEADOS_IDX;

CREATE INDEX CLAVE_LIDER_CENTRO_LID_FK
        ON CENTRO_LIDER (EMPLEADO_ID)
TABLESPACE TS_EMPLEADOS_IDX;

/*==============================================================
  CERTIFICACIONES  –  TS_CERTIFICACIONES_*
==============================================================*/
CREATE TABLE CERTIFICACION (
    CERTIFICACION_ID      VARCHAR2(40) NOT NULL,
    ASOCIACION_ID         VARCHAR2(40),
    NOMBRE_CERTIFICACION  VARCHAR2(40) NOT NULL,
    CONSTRAINT CERTIFICACION_PK PRIMARY KEY (CERTIFICACION_ID)
) TABLESPACE TS_CERTIFICACIONES_DATA;

CREATE INDEX CLAVE_ASOC_CERT_FK
        ON CERTIFICACION (ASOCIACION_ID)
TABLESPACE TS_CERTIFICACIONES_IDX;

CREATE TABLE CERTIFICACION_VERSION (
    CERTIFICACION_VERSION_ID NUMBER(10,0) NOT NULL,
    VERSION_NO_CERTIFICACION NUMBER(38,0) NOT NULL,
    TEMARIO_PDF_VERSION      BLOB         NOT NULL,
    NIVEL_VERSION            VARCHAR2(40) NOT NULL,
    OBJETIVO_VERSION         VARCHAR2(40) NOT NULL,
    CERTIFICACION_ID         VARCHAR2(40),
    CONSTRAINT CERTIFICACION_VERSION_PK PRIMARY KEY (CERTIFICACION_VERSION_ID)
) TABLESPACE TS_CERTIFICACIONES_DATA
  LOB (TEMARIO_PDF_VERSION) STORE AS (
        TABLESPACE TS_CERTIFICACIONES_BLOB
        ENABLE STORAGE IN ROW
        CHUNK 32K );

CREATE UNIQUE INDEX CERTIFICACION_VERSION_UNIQUE
        ON CERTIFICACION_VERSION (VERSION_NO_CERTIFICACION)
TABLESPACE TS_CERTIFICACIONES_IDX;

CREATE INDEX CLAVE_CERT_CERT_VERSION_FK
        ON CERTIFICACION_VERSION (CERTIFICACION_ID)
TABLESPACE TS_CERTIFICACIONES_IDX;

CREATE TABLE LIDER_CERTIFICACION (
    EMPLEADO_ID              VARCHAR2(40) NOT NULL,
    CERTIFICACION_VERSION_ID NUMBER(10,0) NOT NULL,
    FECHA_CERTIFIACION       TIMESTAMP(6) NOT NULL,
    VERSION                  VARCHAR2(40) NOT NULL,
    CONSTRAINT LIDER_CERTIFICACION_PK PRIMARY KEY (EMPLEADO_ID, CERTIFICACION_VERSION_ID)
) TABLESPACE TS_CERTIFICACIONES_DATA;

CREATE INDEX CLAVE_CERT_VER_LIDER_CERT_FK
        ON LIDER_CERTIFICACION (CERTIFICACION_VERSION_ID)
TABLESPACE TS_CERTIFICACIONES_IDX;

CREATE INDEX CLAVE_LIDER_LIDER_CERT_FK
        ON LIDER_CERTIFICACION (EMPLEADO_ID)
TABLESPACE TS_CERTIFICACIONES_IDX;

/*==============================================================
  ACTIVIDADES & TIPOS  –  TS_ACTIVIDADES_*
==============================================================*/
CREATE TABLE ACTIVIDAD (
    ACTIVIDAD_ID          VARCHAR2(40) NOT NULL,
    FECHA_FIN_TEMP        TIMESTAMP(6),
    FECHA_INICIO_TEMP     TIMESTAMP(6),
    COSTO_ACTIVIDAD       VARCHAR2(40) NOT NULL,
    DESCRIPCION_ACTIVIDAD VARCHAR2(40) NOT NULL,
    CENTRO_ID             VARCHAR2(40) NOT NULL,
    EMPLEADO_ID           VARCHAR2(40) NOT NULL,
    CONSTRAINT ACTIVIDAD_PK PRIMARY KEY (ACTIVIDAD_ID)
) TABLESPACE TS_ACTIVIDADES_DATA;

CREATE INDEX CLAVE_CENTRO_VAC_ACTIVIDAD_FK
        ON ACTIVIDAD (CENTRO_ID)
TABLESPACE TS_ACTIVIDADES_IDX;

CREATE INDEX CLAVE_LIDER_ACTIVIDAD_FK
        ON ACTIVIDAD (EMPLEADO_ID)
TABLESPACE TS_ACTIVIDADES_IDX;

CREATE TABLE IMAGEN_ACTIVIDAD (
    IMAGEN_ACTIVIDAD_ID VARCHAR2(40) NOT NULL,
    DATA_IMAGEN         BLOB         NOT NULL,
    ACTIVIDAD_ID        VARCHAR2(40) NOT NULL,
    CONSTRAINT IMAGEN_ACTIVIDAD_PK PRIMARY KEY (IMAGEN_ACTIVIDAD_ID)
) TABLESPACE TS_ACTIVIDADES_DATA
  LOB (DATA_IMAGEN) STORE AS (
        TABLESPACE TS_ACTIVIDADES_BLOB
        ENABLE STORAGE IN ROW
        CHUNK 32K );

CREATE INDEX CLAVE_ACTIVIDAD_IMAG_ACTIVIDAD_FK
        ON IMAGEN_ACTIVIDAD (ACTIVIDAD_ID)
TABLESPACE TS_ACTIVIDADES_IDX;

CREATE TABLE ACTIVIDAD_CAMPAMENTO (
    ACTIVIDAD_ID                  VARCHAR2(40) NOT NULL,
    DURACION_CAMPAMENTO           VARCHAR2(40) NOT NULL,
    UBICACION_LONGITUD_CAMPAMENTO BINARY_FLOAT NOT NULL,
    UBICACION_LATITUD_CAMPAMENTO  BINARY_FLOAT NOT NULL,
    CALLE_CAMPAMENTO              VARCHAR2(40) NOT NULL,
    COLONIA_CAMPAMENTO            VARCHAR2(40) NOT NULL,
    MUNICIPIO_CAMPAMENTO          VARCHAR2(40) NOT NULL,
    CONSTRAINT ACTVIDAD_CAMPAMENTO_PK PRIMARY KEY (ACTIVIDAD_ID)
) TABLESPACE TS_ACTIVIDADES_DATA;

CREATE INDEX ACTIVIDAD_CAMPAMENTO_ID_IX
        ON ACTIVIDAD_CAMPAMENTO (ACTIVIDAD_ID)
TABLESPACE TS_ACTIVIDADES_IDX;

CREATE TABLE ACTIVIDAD_DEPORTE (
    ACTIVIDAD_ID        VARCHAR2(40) NOT NULL,
    NOMBRE_DEPORTE      VARCHAR2(40) NOT NULL,
    DESCRIPCION_DEPORTE VARCHAR2(40) NOT NULL,
    TIPO_DEPORTE_ID     VARCHAR2(40) NOT NULL,
    CONSTRAINT ACTIVIDAD_DEPORTE_PK PRIMARY KEY (ACTIVIDAD_ID)
) TABLESPACE TS_ACTIVIDADES_DATA;

CREATE INDEX CLAVE_ACTIVIDAD_DEPORTE_FK
        ON ACTIVIDAD_DEPORTE (ACTIVIDAD_ID)
TABLESPACE TS_ACTIVIDADES_IDX;

CREATE INDEX CLAVE_TIPO_DEPORTE_ACTIVIDAD_DEPORTE_FK
        ON ACTIVIDAD_DEPORTE (TIPO_DEPORTE_ID)
TABLESPACE TS_ACTIVIDADES_IDX;

CREATE TABLE ACTIVIDAD_JUEGO (
    ACTIVIDAD_ID      VARCHAR2(40) NOT NULL,
    NOMBRE_JUEGO      VARCHAR2(40) NOT NULL,
    DESCRIPCION_JUEGO VARCHAR2(40) NOT NULL,
    TIPO_JUEGO_ID     VARCHAR2(40) NOT NULL,
    CONSTRAINT ACTIVIDAD_JUEGO_PK PRIMARY KEY (ACTIVIDAD_ID)
) TABLESPACE TS_ACTIVIDADES_DATA;

CREATE INDEX "CLAVE_ACTIVIDAD_JUEGO_FK"
        ON ACTIVIDAD_JUEGO (ACTIVIDAD_ID)
TABLESPACE TS_ACTIVIDADES_IDX;

CREATE INDEX CLAVE_TIPO_JUEGO_ACT_JUEGO_FK
        ON ACTIVIDAD_JUEGO (TIPO_JUEGO_ID)
TABLESPACE TS_ACTIVIDADES_IDX;

CREATE TABLE TIPO_DEPORTE (
    TIPO_DEPORTE_ID             VARCHAR2(40) NOT NULL,
    HORAS_ENTRENAMIENTO_DEPORTE VARCHAR2(40) NOT NULL,
    ACCESORIOS_DEPORTE          VARCHAR2(40) NOT NULL,
    NOMBRE_DEPORTE              VARCHAR2(40) NOT NULL,
    CONSTRAINT TIPO_DEPORTE_ID_IX PRIMARY KEY (TIPO_DEPORTE_ID)
) TABLESPACE TS_ACTIVIDADES_DATA;

CREATE TABLE TIPO_JUEGO (
    TIPO_JUEGO_ID                VARCHAR2(40)  NOT NULL,
    NOMBRE                       VARCHAR2(40)  NOT NULL,
    DESCRIPCION_JUEGO            VARCHAR2(40)  NOT NULL,
    CANTIDAD_PARTICIPANTES_JUEGO NUMBER(38,0)  NOT NULL
                                   CHECK (CANTIDAD_PARTICIPANTES_JUEGO > 1),
    CONSTRAINT TIPO_JUEGO_ID_IX  PRIMARY KEY (TIPO_JUEGO_ID)
) TABLESPACE TS_ACTIVIDADES_DATA;

